// data.js
const today = new Date();
const futureDate = new Date();
futureDate.setDate(today.getDate() + 30);
const pastDate = new Date();
pastDate.setDate(today.getDate() - 5);
const anotherFutureDate = new Date();
anotherFutureDate.setDate(today.getDate() + 15);


const initialData = {
  provincias: [
    { id: '02', nombre: 'Ciudad Autónoma de Buenos Aires' },
    { id: '06', nombre: 'Buenos Aires' },
    { id: '10', nombre: 'Catamarca' },
    { id: '14', nombre: 'Córdoba' },
    { id: '18', nombre: 'Corrientes' },
    { id: '22', nombre: 'Chaco' },
    { id: '26', nombre: 'Chubut' },
    { id: '30', nombre: 'Entre Ríos' },
    { id: '34', nombre: 'Formosa' },
    { id: '38', nombre: 'Jujuy' },
    { id: '42', nombre: 'La Pampa' },
    { id: '46', nombre: 'La Rioja' },
    { id: '50', nombre: 'Mendoza' },
    { id: '54', nombre: 'Misiones' },
    { id: '58', nombre: 'Neuquén' },
    { id: '62', nombre: 'Río Negro' },
    { id: '66', nombre: 'Salta' },
    { id: '70', nombre: 'San Juan' },
    { id: '74', nombre: 'San Luis' },
    { id: '78', nombre: 'Santa Cruz' },
    { id: '82', nombre: 'Santa Fe' },
    { id: '86', nombre: 'Santiago del Estero' },
    { id: '90', nombre: 'Tucumán' },
    { id: '94', nombre: 'Tierra del Fuego, Antártida e Islas del Atlántico Sur' },
  ],
  ciudades: [
    { id: 'c1', nombre: 'CABA', provinciaId: '02' },
    // Buenos Aires (06)
    { id: '060007', nombre: 'Adolfo Alsina', provinciaId: '06' },
    { id: '060014', nombre: 'Adolfo Gonzales Chaves', provinciaId: '06' },
    { id: '060021', nombre: 'Alberti', provinciaId: '06' },
    { id: '060028', nombre: 'Almirante Brown', provinciaId: '06' },
    { id: '060035', nombre: 'Avellaneda', provinciaId: '06' },
    { id: '060042', nombre: 'Ayacucho', provinciaId: '06' },
    { id: '060049', nombre: 'Azul', provinciaId: '06' },
    { id: '060056', nombre: 'Bahía Blanca', provinciaId: '06' },
    { id: '060063', nombre: 'Balcarce', provinciaId: '06' },
    { id: '060070', nombre: 'Baradero', provinciaId: '06' },
    { id: '060077', nombre: 'Arrecifes', provinciaId: '06' },
    { id: '060084', nombre: 'Benito Juárez', provinciaId: '06' },
    { id: '060091', nombre: 'Berazategui', provinciaId: '06' },
    { id: '060098', nombre: 'Berisso', provinciaId: '06' },
    { id: '060105', nombre: 'Bolívar', provinciaId: '06' },
    { id: '060112', nombre: 'Bragado', provinciaId: '06' },
    { id: '060119', nombre: 'Brandsen', provinciaId: '06' },
    { id: '060126', nombre: 'Campana', provinciaId: '06' },
    { id: '060133', nombre: 'Cañuelas', provinciaId: '06' },
    { id: '060140', nombre: 'Capitán Sarmiento', provinciaId: '06' },
    { id: '060147', nombre: 'Carlos Casares', provinciaId: '06' },
    { id: '060154', nombre: 'Carlos Tejedor', provinciaId: '06' },
    { id: '060161', nombre: 'Carmen de Areco', provinciaId: '06' },
    { id: '060168', nombre: 'Castelli', provinciaId: '06' },
    { id: '060175', nombre: 'Colón', provinciaId: '06' },
    { id: '060182', nombre: 'Coronel de Marina Leonardo Rosales', provinciaId: '06' },
    { id: '060189', nombre: 'Coronel Dorrego', provinciaId: '06' },
    { id: '060196', nombre: 'Coronel Pringles', provinciaId: '06' },
    { id: '060203', nombre: 'Coronel Suárez', provinciaId: '06' },
    { id: '060210', nombre: 'Chacabuco', provinciaId: '06' },
    { id: '060217', nombre: 'Chascomús', provinciaId: '06' },
    { id: '060224', nombre: 'Chivilcoy', provinciaId: '06' },
    { id: '060231', nombre: 'Daireaux', provinciaId: '06' },
    { id: '060238', nombre: 'Dolores', provinciaId: '06' },
    { id: '060245', nombre: 'Ensenada', provinciaId: '06' },
    { id: '060252', nombre: 'Escobar', provinciaId: '06' },
    { id: '060259', nombre: 'Esteban Echeverría', provinciaId: '06' },
    { id: '060266', nombre: 'Exaltación de la Cruz', provinciaId: '06' },
    { id: '060273', nombre: 'Ezeiza', provinciaId: '06' },
    { id: '060280', nombre: 'Florencio Varela', provinciaId: '06' },
    { id: '060287', nombre: 'Florentino Ameghino', provinciaId: '06' },
    { id: '060294', nombre: 'General Alvarado', provinciaId: '06' },
    { id: '060301', nombre: 'General Alvear', provinciaId: '06' },
    { id: '060308', nombre: 'General Arenales', provinciaId: '06' },
    { id: '060315', nombre: 'General Belgrano', provinciaId: '06' },
    { id: '060322', nombre: 'General Guido', provinciaId: '06' },
    { id: '060329', nombre: 'General Juan Madariaga', provinciaId: '06' },
    { id: '060336', nombre: 'General La Madrid', provinciaId: '06' },
    { id: '060343', nombre: 'General Las Heras', provinciaId: '06' },
    { id: '060350', nombre: 'General Lavalle', provinciaId: '06' },
    { id: '060357', nombre: 'General Paz', provinciaId: '06' },
    { id: '060364', nombre: 'General Rodríguez', provinciaId: '06' },
    { id: '060371', nombre: 'General San Martín', provinciaId: '06' },
    { id: '060378', nombre: 'General Viamonte', provinciaId: '06' },
    { id: '060385', nombre: 'General Villegas', provinciaId: '06' },
    { id: '060392', nombre: 'Guaminí', provinciaId: '06' },
    { id: '060399', nombre: 'Hipólito Yrigoyen', provinciaId: '06' },
    { id: '060406', nombre: 'Hurlingham', provinciaId: '06' },
    { id: '060410', nombre: 'Ituzaingó', provinciaId: '06' },
    { id: '060413', nombre: 'José C. Paz', provinciaId: '06' },
    { id: '060420', nombre: 'Junín', provinciaId: '06' },
    { id: '060427', nombre: 'La Costa', provinciaId: '06' },
    { id: '060434', nombre: 'La Matanza', provinciaId: '06' },
    { id: '060441', nombre: 'Lanús', provinciaId: '06' },
    { id: '060448', nombre: 'La Plata', provinciaId: '06' },
    { id: '060455', nombre: 'Laprida', provinciaId: '06' },
    { id: '060462', nombre: 'Las Flores', provinciaId: '06' },
    { id: '060469', nombre: 'Leandro N. Alem', provinciaId: '06' },
    { id: '060476', nombre: 'Lincoln', provinciaId: '06' },
    { id: '060483', nombre: 'Lobería', provinciaId: '06' },
    { id: '060490', nombre: 'Lobos', provinciaId: '06' },
    { id: '060497', nombre: 'Lomas de Zamora', provinciaId: '06' },
    { id: '060504', nombre: 'Luján', provinciaId: '06' },
    { id: '060511', nombre: 'Magdalena', provinciaId: '06' },
    { id: '060515', nombre: 'Maipú', provinciaId: '06' },
    { id: '060518', nombre: 'Malvinas Argentinas', provinciaId: '06' },
    { id: '060525', nombre: 'Mar Chiquita', provinciaId: '06' },
    { id: '060532', nombre: 'Marcos Paz', provinciaId: '06' },
    { id: '060539', nombre: 'Mercedes', provinciaId: '06' },
    { id: '060546', nombre: 'Merlo', provinciaId: '06' },
    { id: '060553', nombre: 'Monte', provinciaId: '06' },
    { id: '060560', nombre: 'Monte Hermoso', provinciaId: '06' },
    { id: '060567', nombre: 'Moreno', provinciaId: '06' },
    { id: '060574', nombre: 'Morón', provinciaId: '06' },
    { id: '060581', nombre: 'Navarro', provinciaId: '06' },
    { id: '060588', nombre: 'Necochea', provinciaId: '06' },
    { id: '060595', nombre: 'Nueve de Julio', provinciaId: '06' },
    { id: '060602', nombre: 'Olavarría', provinciaId: '06' },
    { id: '060609', nombre: 'Patagones', provinciaId: '06' },
    { id: '060616', nombre: 'Pehuajó', provinciaId: '06' },
    { id: '060623', nombre: 'Pellegrini', provinciaId: '06' },
    { id: '060630', nombre: 'Pergamino', provinciaId: '06' },
    { id: '060637', nombre: 'Pila', provinciaId: '06' },
    { id: '060644', nombre: 'Pilar', provinciaId: '06' },
    { id: '060651', nombre: 'Pinamar', provinciaId: '06' },
    { id: '060658', nombre: 'Presidente Perón', provinciaId: '06' },
    { id: '060665', nombre: 'Puán', provinciaId: '06' },
    { id: '060672', nombre: 'Punta Indio', provinciaId: '06' },
    { id: '060679', nombre: 'Quilmes', provinciaId: '06' },
    { id: '060686', nombre: 'Ramallo', provinciaId: '06' },
    { id: '060693', nombre: 'Rauch', provinciaId: '06' },
    { id: '060700', nombre: 'Rivadavia', provinciaId: '06' },
    { id: '060707', nombre: 'Rojas', provinciaId: '06' },
    { id: '060714', nombre: 'Roque Pérez', provinciaId: '06' },
    { id: '060721', nombre: 'Saavedra', provinciaId: '06' },
    { id: '060728', nombre: 'Saladillo', provinciaId: '06' },
    { id: '060735', nombre: 'Salto', provinciaId: '06' },
    { id: '060742', nombre: 'Salliqueló', provinciaId: '06' },
    { id: '060749', nombre: 'San Andrés de Giles', provinciaId: '06' },
    { id: '060756', nombre: 'San Antonio de Areco', provinciaId: '06' },
    { id: '060763', nombre: 'San Cayetano', provinciaId: '06' },
    { id: '060770', nombre: 'San Fernando', provinciaId: '06' },
    { id: '060777', nombre: 'San Isidro', provinciaId: '06' },
    { id: '060784', nombre: 'San Miguel', provinciaId: '06' },
    { id: '060791', nombre: 'San Nicolás', provinciaId: '06' },
    { id: '060798', nombre: 'San Pedro', provinciaId: '06' },
    { id: '060805', nombre: 'San Vicente', provinciaId: '06' },
    { id: '060812', nombre: 'Suipacha', provinciaId: '06' },
    { id: '060819', nombre: 'Tandil', provinciaId: '06' },
    { id: '060826', nombre: 'Tapalqué', provinciaId: '06' },
    { id: '060833', nombre: 'Tigre', provinciaId: '06' },
    { id: '060840', nombre: 'Tordillo', provinciaId: '06' },
    { id: '060847', nombre: 'Tornquist', provinciaId: '06' },
    { id: '060854', nombre: 'Trenque Lauquen', provinciaId: '06' },
    { id: '060861', nombre: 'Tres Arroyos', provinciaId: '06' },
    { id: '060868', nombre: 'Tres de Febrero', provinciaId: '06' },
    { id: '060875', nombre: 'Tres Lomas', provinciaId: '06' },
    { id: '060882', nombre: 'Veinticinco de Mayo', provinciaId: '06' },
    { id: '060889', nombre: 'Vicente López', provinciaId: '06' },
    { id: '060896', nombre: 'Villa Gesell', provinciaId: '06' },
    { id: '060903', nombre: 'Villarino', provinciaId: '06' },
    { id: '060910', nombre: 'Zárate', provinciaId: '06' },
    // Cordoba (14)
    { id: 'c4', nombre: 'Córdoba Capital', provinciaId: '14' },
    { id: 'c5', nombre: 'Villa Carlos Paz', provinciaId: '14' },
    // Santa Fe (82)
    { id: 'c6', nombre: 'Rosario', provinciaId: '82' },
    { id: 'c7', nombre: 'Santa Fe Capital', provinciaId: '82' },
    // Mendoza (50)
    { id: 'c8', nombre: 'Mendoza Capital', provinciaId: '50' },
    { id: 'c9', nombre: 'San Rafael', provinciaId: '50' },
  ],
  rubros: [
    { id: 'r1', nombre: 'Gastronomía', icon: '🍔' },
    { id: 'r2', nombre: 'Indumentaria y Accesorios', icon: '👕' },
    { id: 'r3', nombre: 'Tecnología', icon: '💻' },
    { id: 'r4', nombre: 'Profesionales y Oficios', icon: '🛠️' },
    { id: 'r5', nombre: 'Turismo y Hotelería', icon: '✈️' },
    { id: 'r6', nombre: 'Hogar y Construcción', icon: '🏠' },
    { id: 'r7', nombre: 'Salud', icon: '⚕️' },
    { id: 'r8', nombre: 'Belleza', icon: '💅' },
    { id: 'r9', nombre: 'Vehículos y Propiedades', icon: '🚗' },
  ],
  subRubros: [
    { id: 'sr1', nombre: 'Restaurante', rubroId: 'r1' },
    { id: 'sr2', nombre: 'Pizzería', rubroId: 'r1' },
    { id: 'sr3', nombre: 'Cafetería', rubroId: 'r1' },
    { id: 'sr4', nombre: 'Heladería', rubroId: 'r1' },
    { id: 'sr5', nombre: 'Bar', rubroId: 'r1' },
    { id: 'sr6', nombre: 'Cervecería', rubroId: 'r1' },
    { id: 'sr_g1', nombre: 'Comidas Caseras', rubroId: 'r1' },
    { id: 'sr_g2', nombre: 'Rotisería', rubroId: 'r1' },
    { id: 'sr_g3', nombre: 'Dulces y Repostería', rubroId: 'r1' },
    { id: 'sr_g4', nombre: 'Catering para Fiestas', rubroId: 'r1' },
    { id: 'sr7', nombre: 'Ropa de Mujer', rubroId: 'r2' },
    { id: 'sr8', nombre: 'Ropa de Hombre', rubroId: 'r2' },
    { id: 'sr9', nombre: 'Ropa de Niños', rubroId: 'r2' },
    { id: 'sr10', nombre: 'Zapatería', rubroId: 'r2' },
    { id: 'sr11', nombre: 'Lencería', rubroId: 'r2' },
    { id: 'sr12', nombre: 'Venta de Equipos', rubroId: 'r3' },
    { id: 'sr13', nombre: 'Servicio Técnico de PC', rubroId: 'r3' },
    { id: 'sr14', nombre: 'Reparación de Celulares', rubroId: 'r3' },
    { id: 'sr_t1', nombre: 'Venta de Electrodomésticos', rubroId: 'r3' },
    { id: 'sr_t2', nombre: 'Electrónica', rubroId: 'r3' },
    { id: 'sr17', nombre: 'Plomería', rubroId: 'r4' },
    { id: 'sr18', nombre: 'Electricista', rubroId: 'r4' },
    { id: 'sr_po1', nombre: 'Abogados', rubroId: 'r4' },
    { id: 'sr_po2', nombre: 'Arquitectos', rubroId: 'r4' },
    { id: 'sr_po3', nombre: 'Ingenieros', rubroId: 'r4' },
    { id: 'sr_po4', nombre: 'Gasista', rubroId: 'r4' },
    { id: 'sr_po5', nombre: 'Albañil', rubroId: 'r4' },
    { id: 'sr_po6', nombre: 'Pintor', rubroId: 'r4' },
    { id: 'sr_po7', nombre: 'Estudio Contable', rubroId: 'r4' },
    { id: 'sr_po8', nombre: 'Taller Mecánico', rubroId: 'r4' },
    { id: 'sr20', nombre: 'Hotel', rubroId: 'r5' },
    { id: 'sr21', nombre: 'Agencia de Viajes', rubroId: 'r5' },
    { id: 'sr22', nombre: 'Alquiler de Cabañas', rubroId: 'r5' },
    { id: 'sr23', nombre: 'Excursiones', rubroId: 'r5' },
    { id: 'sr_hc1', nombre: 'Muebles', rubroId: 'r6' },
    { id: 'sr_hc2', nombre: 'Cocina', rubroId: 'r6' },
    { id: 'sr_hc3', nombre: 'Jardín', rubroId: 'r6' },
    { id: 'sr_hc4', nombre: 'Seguridad', rubroId: 'r6' },
    { id: 'sr_hc5', nombre: 'Iluminación', rubroId: 'r6' },
    { id: 'sr_hc6', nombre: 'Organización del Hogar', rubroId: 'r6' },
    { id: 'sr_s1', nombre: 'Médicos', rubroId: 'r7' },
    { id: 'sr_s2', nombre: 'Enfermeros', rubroId: 'r7' },
    { id: 'sr_s3', nombre: 'Kinesiólogos', rubroId: 'r7' },
    { id: 'sr_s4', nombre: 'Masajistas', rubroId: 'r7' },
    { id: 'sr_s5', nombre: 'Psicólogos', rubroId: 'r7' },
    { id: 'sr_s6', nombre: 'Psicopedagogos', rubroId: 'r7' },
    { id: 'sr_s7', nombre: 'Asistente Terapéutico', rubroId: 'r7' },
    { id: 'sr_b1', nombre: 'Spa', rubroId: 'r8' },
    { id: 'sr_b2', nombre: 'Estética', rubroId: 'r8' },
    { id: 'sr_b3', nombre: 'Depilación', rubroId: 'r8' },
    { id: 'sr_b4', nombre: 'Uñas', rubroId: 'r8' },
    { id: 'sr_b5', nombre: 'Peluquería', rubroId: 'r8' },
    { id: 'sr_vp1', nombre: 'Venta y Alquiler de Propiedades', rubroId: 'r9' },
    { id: 'sr_vp2', nombre: 'Venta de Vehículos', rubroId: 'r9' },
  ],
  usuarios: [
    { id: 'u1', nombre: 'Juan Perez', email: 'juan.perez@example.com', password: 'password123', telefono: '1122334455', isVerified: true },
    { id: 'u2', nombre: 'Maria Gomez', email: 'maria.gomez@example.com', password: 'password123', telefono: '3512233445', isVerified: true },
    { id: 'u3', nombre: 'Carlos Lopez', email: 'carlos.lopez@example.com', password: 'password123', telefono: null, isVerified: true },
    { id: 'u4', nombre: 'Ana Fernandez', email: 'ana.fernandez@example.com', password: 'password123', telefono: '2212233445', isVerified: true },
    { id: 'u5', nombre: 'Luis Martinez', email: 'luis.martinez@example.com', password: 'password123', telefono: null, isVerified: true },
    { id: 'u6', nombre: 'Sofia Rodriguez', email: 'sofia.rodriguez@example.com', password: 'password123', telefono: null, isVerified: true },
  ],
  comercios: [
    { id: 'co1', nombre: 'La Pizzería de Juan', imagenUrl: 'https://picsum.photos/400/300?random=1', rubroId: 'r1', subRubroId: 'sr2', provinciaId: '02', provinciaNombre: 'Ciudad Autónoma de Buenos Aires', ciudadId: 'c1', ciudadNombre: 'CABA', barrio: 'Palermo', usuarioId: 'u1', whatsapp: '5491112345678', direccion: 'Av. Corrientes 1234', googleMapsUrl: 'https://www.google.com/maps', websiteUrl: 'https://example.com', description: 'La mejor pizza de la ciudad, con ingredientes frescos y horno de barro. Más de 20 años de experiencia.', galeriaImagenes: ['https://picsum.photos/800/600?random=11', 'https://picsum.photos/800/600?random=12', 'https://picsum.photos/800/600?random=13'], publicidad: 6, vencimientoPublicidad: futureDate.toISOString(), renovacionAutomatica: true, lat: -34.588, lon: -58.421, opiniones: [
        { id: 'op1-1', usuarioId: 'pub-user-1', usuarioNombre: 'Ana G.', rating: 5, texto: '¡La mejor pizza de la ciudad! El lugar es muy acogedor y la atención de primera. Siempre volvemos.', timestamp: new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(), likes: ['pub-user-2', 'pub-user-3'] },
        { id: 'op1-2', usuarioId: 'pub-user-2', usuarioNombre: 'Marcos R.', rating: 4, texto: 'Muy buena pizza, aunque tardaron un poco en traerla un sábado a la noche. Recomendable de todas formas.', timestamp: new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(), likes: [], respuesta: { texto: '¡Gracias por tu reseña, Marcos! Nos alegra que te haya gustado. Estamos trabajando para mejorar los tiempos de espera los fines de semana. ¡Te esperamos de nuevo!', timestamp: new Date(today.getTime() - 12 * 60 * 60 * 1000).toISOString() } },
    ]},
    { id: 'co2', nombre: 'Boutique María', imagenUrl: 'https://picsum.photos/400/300?random=2', rubroId: 'r2', subRubroId: 'sr7', provinciaId: '14', provinciaNombre: 'Córdoba', ciudadId: 'c4', ciudadNombre: 'Córdoba Capital', barrio: 'Nueva Córdoba', usuarioId: 'u2', whatsapp: '5493511234567', direccion: 'Av. Colón 500', googleMapsUrl: 'https://www.google.com/maps', websiteUrl: 'https://example.com', description: 'Ropa de diseño exclusivo para mujeres modernas. Últimas tendencias de la moda europea.', galeriaImagenes: ['https://picsum.photos/800/600?random=21'], publicidad: 5, vencimientoPublicidad: futureDate.toISOString(), renovacionAutomatica: false, lat: -31.417, lon: -64.183, opiniones: [
        { id: 'op2-1', usuarioId: 'pub-user-3', usuarioNombre: 'Lucía F.', rating: 5, texto: '¡Amo este lugar! Siempre encuentro ropa única y de excelente calidad. La dueña es un amor.', timestamp: new Date().toISOString(), likes: [] },
    ]},
    { id: 'co3', nombre: 'Tech Shop', imagenUrl: 'https://picsum.photos/400/300?random=3', rubroId: 'r3', subRubroId: 'sr12', provinciaId: '82', provinciaNombre: 'Santa Fe', ciudadId: 'c6', ciudadNombre: 'Rosario', barrio: 'Centro', usuarioId: 'u3', whatsapp: '5493411234567', direccion: '', googleMapsUrl: '', websiteUrl: '', description: '', publicidad: 1, renovacionAutomatica: false, lat: -32.947, lon: -60.63, opiniones: [
         { id: 'op3-1', usuarioId: 'pub-user-4', usuarioNombre: 'Pedro M.', rating: 3, timestamp: new Date().toISOString(), likes: [] },
    ]},
    { id: 'co4', nombre: 'Plomero 24hs', imagenUrl: 'https://picsum.photos/400/300?random=4', rubroId: 'r4', subRubroId: 'sr17', provinciaId: '06', provinciaNombre: 'Buenos Aires', ciudadId: '060448', ciudadNombre: 'La Plata', barrio: '', usuarioId: 'u4', whatsapp: '5492211234567', direccion: '', googleMapsUrl: '', websiteUrl: '', description: 'Servicio de plomería y gasista matriculado. Urgencias las 24 horas en La Plata y alrededores.', publicidad: 2, vencimientoPublicidad: anotherFutureDate.toISOString(), renovacionAutomatica: true, lat: -34.921, lon: -57.954, opiniones: [
        { id: 'op4-1', usuarioId: 'pub-user-5', usuarioNombre: 'Jorge L.', rating: 5, texto: 'Me salvó un domingo a la madrugada con una inundación. Súper profesional y rápido.', timestamp: new Date().toISOString(), likes: [] },
    ]},
    { id: 'co5', nombre: 'Excursiones Mendoza', imagenUrl: 'https://picsum.photos/400/300?random=5', rubroId: 'r5', subRubroId: 'sr23', provinciaId: '50', provinciaNombre: 'Mendoza', ciudadId: 'c8', ciudadNombre: 'Mendoza Capital', barrio: '', usuarioId: 'u5', whatsapp: '5492611234567', direccion: '', googleMapsUrl: '', websiteUrl: '', description: '', galeriaImagenes: ['https://picsum.photos/800/600?random=51', 'https://picsum.photos/800/600?random=52'], publicidad: 5, vencimientoPublicidad: futureDate.toISOString(), renovacionAutomatica: true, lat: -32.889, lon: -68.845, opiniones: [
        { id: 'op5-1', usuarioId: 'pub-user-1', usuarioNombre: 'Ana G.', rating: 4, texto: 'Hicimos la excursión de alta montaña, los paisajes increíbles. El guía un genio.', timestamp: new Date().toISOString(), likes: [] },
    ]},
    { id: 'co6', nombre: 'Café de la Plaza', imagenUrl: 'https://picsum.photos/400/300?random=6', rubroId: 'r1', subRubroId: 'sr3', provinciaId: '14', provinciaNombre: 'Córdoba', ciudadId: 'c5', ciudadNombre: 'Villa Carlos Paz', barrio: 'Centro', usuarioId: 'u6', whatsapp: '5493541123456', direccion: '', googleMapsUrl: '', websiteUrl: 'https://example.com', description: 'Un lugar acogedor para disfrutar de café de especialidad y pastelería casera frente a la plaza principal.', publicidad: 3, vencimientoPublicidad: anotherFutureDate.toISOString(), renovacionAutomatica: false, lat: -31.424, lon: -64.497, opiniones: [
        { id: 'op6-1', usuarioId: 'pub-user-2', usuarioNombre: 'Marcos R.', rating: 5, texto: 'El mejor café que probé en Carlos Paz.', timestamp: new Date().toISOString(), likes: [] },
        { id: 'op6-2', usuarioId: 'pub-user-3', usuarioNombre: 'Lucía F.', rating: 5, texto: 'La torta de chocolate es un 10!', timestamp: new Date().toISOString(), likes: [] },
    ]},
    { id: 'co7', nombre: 'Ropa Deportiva SF', imagenUrl: 'https://picsum.photos/400/300?random=7', rubroId: 'r2', subRubroId: 'sr8', provinciaId: '82', provinciaNombre: 'Santa Fe', ciudadId: 'c7', ciudadNombre: 'Santa Fe Capital', barrio: '', usuarioId: 'u1', whatsapp: '5493421234567', direccion: '', googleMapsUrl: '', websiteUrl: '', description: '', publicidad: 4, vencimientoPublicidad: futureDate.toISOString(), renovacionAutomatica: true, lat: -31.61, lon: -60.7, opiniones: [] },
  ],
  banners: [
    { id: 'b1', comercioId: 'co2', imagenUrl: 'https://picsum.photos/800/200?random=10', venceEl: futureDate.toISOString() },
    { id: 'b2', comercioId: 'co5', imagenUrl: 'https://picsum.photos/800/200?random=11', venceEl: futureDate.toISOString() },
    { id: 'b3', comercioId: 'co1', imagenUrl: 'https://picsum.photos/800/200?random=12', venceEl: pastDate.toISOString() }, // Vencido
  ],
  pagos: [
    { id: 'pay1', comercioId: 'co2', monto: 5000, fecha: new Date().toISOString(), mercadoPagoId: 'mp123' },
  ],
};

module.exports = { 
  getInitialData: () => JSON.parse(JSON.stringify(initialData))
};